/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.tag.plugin;

import gradle.tag.plugin.task.GitCreateTagTask;
import gradle.tag.plugin.task.GitLastTagTask;
import gradle.tag.plugin.task.GitLastTagVersionTask;
import gradle.tag.plugin.task.GitUncommittedChangeTask;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.gradle.api.Plugin;
import org.gradle.api.Project;

public class GradleGitTagPlugin implements Plugin<Project> {

    private static final Logger log = LogManager.getLogger(GradleGitTagPlugin.class);

    public static final String TASK_GROUP_NAME = "git tag";

    public void apply(Project project) {
        // Register a task
        GitUncommittedChangeTask gitCheckUncommittedChanges =
                project.getTasks().register("gitUncommittedChanges", GitUncommittedChangeTask.class).get();
        gitCheckUncommittedChanges.setGroup(TASK_GROUP_NAME);

        GitLastTagTask lastTag = project.getTasks().register("gitLastTag", GitLastTagTask.class).get();
        lastTag.dependsOn(gitCheckUncommittedChanges).setOnlyIf(task -> !(boolean) gitCheckUncommittedChanges.getExtensions().getByName("result"));
        lastTag.setGroup(TASK_GROUP_NAME);

        GitCreateTagTask createTag = project.getTasks().register("createTag", GitCreateTagTask.class).get();
        createTag.setGroup(TASK_GROUP_NAME);

//        GitLastTagVersionTask gitGetLastVersion = project.getTasks().register("gitLastVersion", GitLastTagVersionTask.class).get();
//        gitGetLastVersion
//                .dependsOn(gitCheckUncommittedChanges)
//                .setOnlyIf(task ->
//                        (boolean) gitCheckUncommittedChanges.getExtensions().getByName("result"));
//        gitGetLastVersion.setGroup(TASK_GROUP_NAME);



    }
}
