/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.tag.plugin;

import gradle.tag.plugin.task.GitLastTagTask;
import gradle.tag.plugin.task.GitLastTagVersionTask;
import gradle.tag.plugin.task.GitUncommittedChangeTask;
import org.gradle.api.Plugin;
import org.gradle.api.Project;

public class GradleGitTagPlugin implements Plugin<Project> {

    public static final String TASK_GROUP_NAME = "git tag";

    public void apply(Project project) {
        // Register a task
        GitUncommittedChangeTask gitCheckUncommittedChanges =
                project.getTasks().register("gitUncommittedChanges", GitUncommittedChangeTask.class).get();
        gitCheckUncommittedChanges.setGroup(TASK_GROUP_NAME);

        GitLastTagTask lastTag = project.getTasks().register("gitLastTag", GitLastTagTask.class).get();
        lastTag.setGroup(TASK_GROUP_NAME);
//        System.out.println(lastTag.getExtensions().getByName("tagValue"));

//        GitLastTagVersionTask gitGetLastVersion = project.getTasks().register("gitLastVersion", GitLastTagVersionTask.class).get();
//        gitGetLastVersion
//                .dependsOn(gitCheckUncommittedChanges)
//                .setOnlyIf(task ->
//                        (boolean) gitCheckUncommittedChanges.getExtensions().getByName("result"));
//        gitGetLastVersion.setGroup(TASK_GROUP_NAME);



    }
}
